version: 2
updates:
  # Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "security-team"
    assignees:
      - "lead-developer"
    commit-message:
      prefix: "security"
      include: "scope"
    labels:
      - "security"
      - "dependencies"
      - "notification-service"
    allow:
      - dependency-type: "direct"
        update-type: "security"
      - dependency-type: "indirect"
        update-type: "security"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "security-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "security"
      - "github-actions"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "security-team"
    assignees:
      - "devops-team"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "security"
      - "docker"
