# =============================================================================
# Diagnyx Notification Service Configuration
# =============================================================================

server:
  port: 8085
  servlet:
    context-path: /api/v1/notifications
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  http2:
    enabled: true

spring:
  application:
    name: notification-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: ${SPRING_DATASOURCE_USERNAME:diagnyx_notification}
    password: ${SPRING_DATASOURCE_PASSWORD:diagnyx_secure_password}
    driver-class-name: org.postgresql.Driver
    
    # HikariCP Configuration - Optimized for production
    hikari:
      pool-name: NotificationServiceHikariPool
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
      validation-timeout: ${DB_VALIDATION_TIMEOUT:5000}
      auto-commit: false
      connection-test-query: SELECT 1

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        connection:
          provider_disables_autocommit: true
        # Cache configuration - simplified
        cache:
          use_second_level_cache: false
          use_query_cache: false
    show-sql: true
    open-in-view: false
    
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    schemas: public

  # H2 Console for development
  h2:
    console:
      enabled: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,hikaricp
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    enable:
      hikaricp: true
      jvm: true
      system: true
      jdbc: true

# Logging Configuration
logging:
  level:
    com.diagnyx: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO
