server:
  port: 8081

spring:
  application:
    name: notification-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/notification-db
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator

logging:
  level:
    com.diagnyx: INFO
    org.hibernate.SQL: DEBUG
